version: '3.8'
name: MHPASSWORDMANAGER
services:
  rabbit-broker:
    image: rabbitmq:3.9-management
    restart: on-failure
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
        - rabbit-data:/var/lib/rabbitmq
        - rabbit-logs:/var/log/rabbitmq
volumes:
  rabbit-data:
    driver: local
  rabbit-logs:
    driver: local