spring:
  application:
    name: file-service
  config:
    import:
      - optional:configserver:${SPRING_CONFIG_SERVER_URI:http://localhost:8888}
server:
  port: 12014
  servlet:
    context-path: /files
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile: test
eureka:
  client:
    enabled: false
