server:
  port: 12010
spring:
  application:
    name: authorization-server
  profiles:
    default: local,enable-actuator,config-springdoc,issuer-local
  mvc:
    static-path-pattern: /content/**
  config:
    import:
      - optional:configserver:${SPRING_CONFIG_SERVER_URI:http://localhost:8888}
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
springdoc:
  version: @project.version@
  title: @project.name@
  description: @project.description@
  license-name: 'MIT'
  license-url: 'https://github.com/marcoshssilva/MHPasswordManager/blob/main/LICENSE'
  swagger-ui:
    oauth2-redirect-url: ${SPRINGDOC_SWAGGERUI_OAUTH2_REDIRECT_URL:http://127.0.0.1:12010/swagger-ui/redirect}
    oauth2-authorization-url: ${SPRINGDOC_SWAGGERUI_OAUTH2_AUTHORIZATION_URL:http://127.0.0.1:12010/oauth2/authorize} # custom, doesnt exists on springdoc open-api
    oauth2-token-url: ${SPRINGDOC_SWAGGERUI_OAUTH2_TOKEN_URL:http://127.0.0.1:12010/oauth2/token} # custom, doesnt exists on springdoc open-api
    csrf:
      enabled: true # enable csrf in swagger-ui requests
---
spring:
  config:
    activate:
      on-profile: test
  session:
    store-type: none
  flyway:
    enabled: false
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    enabled: false
authorization:
  issuer-uri: http://localhost:12010
  success-logout-uri: http://localhost:8100