spring:
  profiles:
    active: test
  application:
    name: 'authorization-server'
  h2:
    console:
      enabled: true
      path: /h2
  redis:
    host: 127.0.0.1
    password: MARCOSHSSILVA#20230101
    port: 6379
  session:
    store-type: redis
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}
authorization:
  issuer-uri: http://localhost:9000
management:
  endpoint:
    health:
      group:
        custom:
          show-components: ALWAYS
          show-details: ALWAYS
          include:
            - diskSpace
            - ping
            - db
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - '*'
