spring:
  application:
    name: 'oauth2'
  h2:
    console:
      enabled: true
      path: /h2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9000
