spring:
  application:
    name: 'authorization-server'
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}
gateway:
  host: http://localhost:8765/authorization-server
authorization:
  issuer-uri: http://localhost:9000
management:
  endpoint:
    health:
      group:
        custom:
          show-components: ALWAYS
          show-details: ALWAYS
          include:
            - diskSpace
            - ping
            - db
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'
