spring:
  application:
    name: 'authorization-server'
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}