spring:
  profiles:
    active: redis
  application:
    name: 'authorization-server'
  mvc:
    static-path-pattern: /content/**
server:
  port: 12010
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
authorization:
  issuer-uri: http://localhost:12010
  success-logout-uri: http://127.0.0.1:8100
management:
  endpoint:
    health:
      group:
        integrations-details:
          show-components: ALWAYS
          show-details: ALWAYS
          include:
            - ping
            - db
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - '*'
springdoc:
  # description
  version: @project.version@
  title: @project.name@
  description: @project.description@
  license-name: 'MIT'
  license-url: 'https://github.com/marcoshssilva/MHPasswordManager/blob/main/LICENSE'
  # enable actuator to Swagger
  show-actuator: true
  # show login-endpoint to Swagger
  show-login-endpoint: true
  swagger-ui:
    csrf:
      enabled: true # enable csrf in swagger-ui requests
---
spring:
  config:
    activate:
      on-profile: test
  session:
    store-type: none
---
spring:
  config:
    activate:
      on-profile: redis
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    password: MARCOSHSSILVA#20230101
    port: 6379
---
spring:
  config:
    activate:
      on-profile: embedded-database
  h2:
    console:
      enabled: true
      path: /h2