spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: password-service
          uri: lb://PASSWORD-SERVICE
          predicates:
            - Path=/passwords/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
            allowedHeaders:
              - Content-type
              - Authorization
  management:
    endpoints:
      web:
        exposure:
          include: '*'
server:
  port: 12050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka