server:
  port: 12050
  ssl:
    enabled: ${SERVER_SERVLET_SSL_ENABLED:false}
    key-alias: ${SERVER_SERVLET_SSL_KEY_ALIAS:}
    key-store: ${SERVER_SERVLET_SSL_KEY_STORE:}
    key-store-type: ${SERVER_SERVLET_SSL_KEY_STORE_TYPE:}
    key-store-password: ${SERVER_SERVLET_SSL_KEY_STORE_PASSWORD:}
    key-password: ${SERVER_SERVLET_SSL_KEY_PASSWORD:}
    trust-store: ${SERVER_SERVLET_SSL_TRUST_STORE:}
    trust-store-password: ${SERVER_SERVLET_SSL_TRUST_STORE_PASSWORD:}
spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
            allowedHeaders:
              - Content-type
              - Authorization
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: password-service
          uri: lb://PASSWORD-SERVICE
          predicates:
            - Path=/passwords/**
        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/emails/**
        - id: file-service
          uri: lb://FILE-SERVICE
          predicates:
            - Path=/files/**

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'metrics'
          - 'info'
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile: test
eureka:
  client:
    enabled: false