server:
  port: 12050
spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
            allowedHeaders:
              - Content-type
              - Authorization
      routes:
        - id: authorization-server
          uri: lb://AUTHORIZATION-SERVER
          predicates:
            - Path=/mypass-manager/auth/**
          filters:
            - PreserveHostHeader
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/mypass-manager/users/**
          filters:
            - RewritePath=/mypass-manager/users/(?<segment>.*),/users/$\{segment}
        - id: password-service
          uri: lb://PASSWORD-SERVICE
          predicates:
            - Path=/mypass-manager/passwords/**
          filters:
            - RewritePath=/mypass-manager/passwords/(?<segment>.*),/passwords/$\{segment}
        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/mypass-manager/emails/**
          filters:
            - RewritePath=/mypass-manager/emails/(?<segment>.*),/emails/$\{segment}
        - id: file-service
          uri: lb://FILE-SERVICE
          predicates:
            - Path=/mypass-manager/files/**
          filters:
            - RewritePath=/mypass-manager/files/(?<segment>.*),/files/$\{segment}
        - id: default_route
          uri: https://dev.marcoshssilva.com.br
          predicates:
            - Path=/**

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'metrics'
          - 'info'
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile: test
eureka:
  client:
    enabled: false