spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERS
          predicates:
            - Path=/users/**
        - id: authorization-server
          uri: lb://AUTHORIZATION-SERVER
          predicates:
            - Path=/oauth2/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
            allowedHeaders:
              - Content-type
              - Authorization
  management:
    endpoints:
      web:
        exposure:
          include: '*'

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}