spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8100"
              - "http://localhost:4200"
              - "http://localhost:8080"
              - "http://localhost"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
  management:
    endpoints:
      web:
        exposure:
          include: '*'

server:
  port: ${PORT:8765}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka