server:
  port: 12050
spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
            allowedHeaders:
              - Content-type
              - Authorization
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: password-service
          uri: lb://PASSWORD-SERVICE
          predicates:
            - Path=/passwords/**
        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/emails/**
        - id: file-service
          uri: lb://FILE-SERVICE
          predicates:
            - Path=/files/**

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'metrics'
          - 'info'
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile: test
eureka:
  client:
    enabled: false