server:
  port: 12013
  servlet:
    context-path: /emails
spring:
  profiles:
    default: local
  application:
    name: email-service
  config:
    import:
      - optional:configserver:${SPRING_CONFIG_SERVER_URI:http://localhost:8888}
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
springdoc:
  version: @project.version@
  title: @project.name@
  description: @project.description@
  license-name: 'MIT'
  license-url: 'https://github.com/marcoshssilva/MHPasswordManager/blob/main/LICENSE'
---
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:12010
  redis:
    host: 127.0.0.1
    password: 'MHP@SSW0R3#20230401'
    port: 12379
  rabbitmq:
    host: 127.0.0.1
    port: 12672
    virtual-host: vhost-password-manager
    username: email-service-pm
    password: email-service-pm-P@ss
  mail:
    host: localhost
    username: je7ls6pyin
    password: 5n4laalrzvtseypixfgl
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.port: 12525
      mail.smtp.starttls.enable: false
      mail.smtp.starttls.required: false
---
spring:
  config:
    activate:
      on-profile: test
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://mhpasswordmanager.test.fake.com
  mail:
    host: localhost
    username: je7ls6pyin
    password: 5n4laalrzvtseypixfgl
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.port: 12525
      mail.smtp.starttls.enable: false
      mail.smtp.starttls.required: false
  session:
    store-type: none
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    enabled: false