server:
  port: 12013
  servlet:
    context-path: /emails
spring:
  profiles:
    default: local
  application:
    name: email-service
  config:
    import:
      - optional:configserver:${SPRING_CONFIG_SERVER_URI:http://localhost:8888}
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
springdoc:
  version: @project.version@
  title: @project.name@
  description: @project.description@
  license-name: 'MIT'
  license-url: 'https://github.com/marcoshssilva/MHPasswordManager/blob/main/LICENSE'
---
spring:
  config:
    activate:
      on-profile: test
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://mhpasswordmanager.test.fake.com
  mail:
    host: test.fake.com
    username: no-reply@test.fake.com
    password: P@ssW0r7
    properties:
      mail.transport.protocol: smtp
      mail.smtp.port: 25
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  session:
    store-type: none
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    enabled: false