version: '3.8'

services:
  mhpasswordmanager-flyway-database-migrations-tool:
    container_name: 'mhpasswordmanager-flyway-database-migrations-tool'
    build:
      context: ../mhpasswordmanager-flyway-database-migrations-tool
      dockerfile: ./docs/Dockerfile
    environment:
      DATABASE_JDBC_URL: 'jdbc:postgresql://host.docker.internal:5432/postgres'
      DATABASE_JDBC_USERNAME: 'postgres'
      DATABASE_JDBC_PASSWORD: 'postgres'
    networks:
      - net-mhpasswordmanager
networks:
  net-mhpasswordmanager: # default for project
    driver: bridge