version: '3.8'
services:
  config-services:
    image: mhpasswordmanager/config-services:latest
    container_name: 'config-services'
    restart: on-failure
    env_file:
      - configs-composable/CONFIG-SERVICES.env
    networks:
      - net-mhpasswordmanager
    ports:
      - "12888:8888"
  eureka-service-discovery:
    image: mhpasswordmanager/service-registry:latest
    container_name: 'eureka-server'
    restart: on-failure
    env_file:
      - configs-composable/SERVICE-REGISTRY.env
    networks:
      - net-mhpasswordmanager
    ports:
      - "12761:8761"
  oauth2-authorization-server:
    container_name: 'authorization-server'
    image: mhpasswordmanager/oauth2-authorization-server:latest
    restart: on-failure
    env_file:
      - configs-composable/OAUTH2-AUTHORIZATION-SERVER.env
    depends_on:
      - redis-store
      - eureka-service-discovery
      - postgres-db
      - config-services
      - rabbitmq
    networks:
      - net-mhpasswordmanager
    ports:
      - "12010:12010"
  api-gateway:
    image: mhpasswordmanager/api-gateway:latest
    container_name: 'api-gateway'
    restart: on-failure
    env_file:
      - configs-composable/API-GATEWAY.env
    depends_on:
      - eureka-service-discovery
    networks:
      - net-mhpasswordmanager
    ports:
      - "12050:12050"
  user-service:
    image: mhpasswordmanager/user-service:latest
    container_name: 'user-service-api'
    restart: on-failure
    env_file:
      - configs-composable/USER-SERVICE.env
    depends_on:
      - eureka-service-discovery
      - postgres-db
      - config-services
      - redis-store
    networks:
      - net-mhpasswordmanager
    ports:
      - "12011:12011"
  password-service:
    image: mhpasswordmanager/password-service:latest
    container_name: 'password-service-api'
    restart: on-failure
    env_file:
      - configs-composable/PASSWORD-SERVICE.env
    depends_on:
      - eureka-service-discovery
      - postgres-db
      - config-services
      - redis-store
    networks:
      - net-mhpasswordmanager
    ports:
      - "12012:12012"
  email-service:
    image: mhpasswordmanager/user-service:latest
    container_name: 'user-service-api'
    restart: on-failure
    env_file:
      - configs-composable/EMAIL-SERVICE.env
    depends_on:
      - eureka-service-discovery
      - config-services
      - redis-store
      - rabbitmq
  postgres-db:
    image: mhpasswordmanager/postgres:latest
    container_name: 'postgres-db'
    restart: on-failure
    env_file:
      - configs-composable/POSTGRES-DB.env
    networks:
      - net-mhpasswordmanager
    ports:
      - "12432:5432"
    volumes:
      - data-mhpasswordmanager-postgres-db:/var/lib/postgresql/data
  redis-store:
    image: mhpasswordmanager/redis:latest
    container_name: 'redis-cache'
    env_file:
      - configs-composable/REDIS-STORE.env
    restart: on-failure
    ports:
      - '12379:6379'
    volumes:
      - data-mhpasswordmanager-redis:/data
    networks:
      - net-mhpasswordmanager
  mongo-db:
    image: mhpasswordmanager/mongo:latest
    container_name: 'mongo-db'
    restart: on-failure
    env_file:
      - configs-composable/MONGO-DB.env
    networks:
      - net-mhpasswordmanager
    volumes:
      - data-mhpasswordmanager-mongo-db:/data/db
    ports:
      - "12717:27017"
  rabbitmq:
    image: mhpasswordmanager/rabbit:latest
    container_name: 'rabbit-broker'
    env_file:
      - configs-composable/RABBITMQ.env
    networks:
      - net-mhpasswordmanager
    volumes:
      - data-mhpasswordmanager-rabbitmq-logs:/var/lib/rabbitmq
      - data-mhpasswordmanager-rabbitmq-logs:/var/log/rabbitmq
    ports:
      - "12672:5672"
      - "12673:15672"
      - "12674:25672"
      - "12692:15692"
networks:
  net-mhpasswordmanager:
    driver: bridge
volumes:
  data-mhpasswordmanager-postgres-db:
  data-mhpasswordmanager-redis:
  data-mhpasswordmanager-mongo-db:
  data-mhpasswordmanager-rabbitmq-logs:
  data-mhpasswordmanager-rabbitmq-data:
