version: '3.8'
services:
  postgres-db:
    image: mhpasswordmanager/postgres:dev
    container_name: 'postgres-db'
    restart: on-failure
    env_file:
      - configs-local/POSTGRES-DB.env
    networks:
      - net-mhpasswordmanager
    ports:
      - "12432:5432"
    volumes:
      - data-mhpasswordmanager-postgres-db:/var/lib/postgresql/data
  redis-store:
    image: mhpasswordmanager/redis:dev
    container_name: 'redis-cache'
    env_file:
      - configs-local/REDIS-STORE.env
    restart: on-failure
    ports:
      - '12379:6379'
    volumes:
      - data-mhpasswordmanager-redis:/data
    networks:
      - net-mhpasswordmanager
  mongo-db:
    image: mhpasswordmanager/mongo:dev
    container_name: 'mongo-db'
    restart: on-failure
    env_file:
      - configs-local/MONGO-DB.env
    networks:
      - net-mhpasswordmanager
    volumes:
      - data-mhpasswordmanager-mongo-db:/data/db
    ports:
      - "12717:27017"
  rabbitmq:
    image: mhpasswordmanager/rabbit:dev
    container_name: 'rabbit-broker'
    env_file:
      - configs-local/RABBITMQ.env
    networks:
      - net-mhpasswordmanager
    volumes:
      - data-mhpasswordmanager-rabbitmq-logs:/var/lib/rabbitmq
      - data-mhpasswordmanager-rabbitmq-logs:/var/log/rabbitmq
    ports:
      - "12672:5672"
      - "12673:15672"
      - "12674:25672"
      - "12692:15692"
networks:
  net-mhpasswordmanager:
    driver: bridge
volumes:
  data-mhpasswordmanager-postgres-db:
  data-mhpasswordmanager-redis:
  data-mhpasswordmanager-mongo-db:
  data-mhpasswordmanager-rabbitmq-logs:
  data-mhpasswordmanager-rabbitmq-data:
