spring:
  application:
    name: 'flyway-database-migrations-tool'
  flyway:
    url: ${DATABASE_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${DATABASE_JDBC_USERNAME:postgres}
    password: ${DATABASE_JDBC_PASSWORD:postgres}
    schemas:
      - 'db_users'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_JDBC_USERNAME:postgres}
    password: ${DATABASE_JDBC_PASSWORD:postgres}
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
