spring:
  application:
    name: eureka-service-registry
server:
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'info'
          - 'metrics'