spring:
  application:
    name: eureka-service-registry
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME:admin}
      password: ${SPRING_SECURITY_PASSWORD:admin}
server:
  servlet:
    ssl:
      enabled: ${SERVER_SERVLET_SSL_ENABLED:false}
      key-alias: ${SERVER_SERVLET_SSL_KEY_ALIAS:}
      key-store: ${SERVER_SERVLET_SSL_KEY_STORE:}
      key-store-type: ${SERVER_SERVLET_SSL_KEY_STORE_TYPE:}
      key-store-password: ${SERVER_SERVLET_SSL_KEY_STORE_PASSWORD:}
      key-password: ${SERVER_SERVLET_SSL_KEY_PASSWORD:}
      trust-store: ${SERVER_SERVLET_SSL_TRUST_STORE:}
      trust-store-password: ${SERVER_SERVLET_SSL_TRUST_STORE_PASSWORD:}
    session:
      cookie:
        http-only: on
        same-site: strict
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:${server.port}/eureka
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'info'
          - 'metrics'