spring:
  application:
    name: eureka-service-registry
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME:admin}
      password: ${SPRING_SECURITY_PASSWORD:admin}
server:
  servlet:
    session:
      cookie:
        http-only: on
        same-site: strict
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:${server.port}/eureka
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'info'
          - 'metrics'