server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
    enabled: true
spring:
  application:
    name: config-server
  profiles:
#   active: native  # native if you need use config from default of this project, reading all .yml files
    active: default # default for use remote git or specific directory to read git config
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_URI:file:///home/marcos/IdeaProjects/MHPasswordManager-Config-Development}
          # optional, don't need if repo is public
          username: ${SPRING_CLOUD_CONFIG_SERVER_USERNAME:}
          # optional, don't need if repo is public
          password: ${SPRING_CLOUD_CONFIG_SERVER_PASSWORD:}
          # if true, always fetch branch 'master'
          try-master-branch: ${SPRING_CLOUD_CONFIG_SERVER_TRY_MASTER_BRANCH:false}
          # default branch to use
          default-label: ${SPRING_CLOUD_CONFIG_SERVER_DEFAULT_LABEL:main}
          # list of sub-folders from git project
          search-paths: ${SPRING_CLOUD_CONFIG_SERVER_SEARCH_PATHS:configs*}

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'metrics'
          - 'info'

---
spring:
  config:
    activate:
      on-profile: test
  cloud:
    config:
      server:
        enabled: false
eureka:
  client:
    enabled: false