server:
  port: 8888
  ssl:
    enabled: ${SERVER_SERVLET_SSL_ENABLED:false}
    key-alias: ${SERVER_SERVLET_SSL_KEY_ALIAS:}
    key-store: ${SERVER_SERVLET_SSL_KEY_STORE:}
    key-store-type: ${SERVER_SERVLET_SSL_KEY_STORE_TYPE:}
    key-store-password: ${SERVER_SERVLET_SSL_KEY_STORE_PASSWORD:}
    key-password: ${SERVER_SERVLET_SSL_KEY_PASSWORD:}
    trust-store: ${SERVER_SERVLET_SSL_TRUST_STORE:}
    trust-store-password: ${SERVER_SERVLET_SSL_TRUST_STORE_PASSWORD:}
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    enabled: true
spring:
  application:
    name: config-server
  profiles:
#   active: native  # native if you need use config from default of this project, reading all .yml files
    active: default # default for use remote git or specific directory to read git config
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_URI:}
          # optional, don't need if repo is public
          username: ${SPRING_CLOUD_CONFIG_SERVER_USERNAME:}
          # optional, don't need if repo is public
          password: ${SPRING_CLOUD_CONFIG_SERVER_PASSWORD:}
          # if true, always fetch branch 'master'
          try-master-branch: ${SPRING_CLOUD_CONFIG_SERVER_TRY_MASTER_BRANCH:false}
          # default branch to use
          default-label: ${SPRING_CLOUD_CONFIG_SERVER_DEFAULT_LABEL:master}
          # list of sub-folders from git project
          search-paths: ${SPRING_CLOUD_CONFIG_SERVER_SEARCH_PATHS:*}
---
spring:
  config:
    activate:
      on-profile: test
  cloud:
    config:
      server:
        enabled: false
eureka:
  client:
    enabled: false