server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    enabled: true
spring:
  application:
    name: config-server
  profiles:
    active: default # default for use remote git or specific directory to read git config
#   active: native  # native if you need use config from default of this project, reading all .yml files

#  cloud:
#    config:
#      enabled: true
#      server:
#        git:
#          uri: https://github.com/someuser/ExampleConfigServer
#          username: my_username # optional, don't need if repo is public
#          password: my_git_pass_or_token # optional, don't need if repo is public
#          try-master-branch: false # if true, always fetch branch 'master'
#          default-label: main # default branch to use
#
#          # list of sub-folders from git project
#          search-paths:
#            - 'configs-marcoshssilva.com.br*'

---
spring:
  config:
    activate:
      on-profile: test
  cloud:
    config:
      server:
        enabled: false
eureka:
  client:
    enabled: false