spring:
  profiles:
    active: redis
  application:
    name: 'user-service'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=db_users
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:12010
#          jwk-set-uri: http://localhost:12010/oauth2/jwks
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  servlet:
    context-path: /users
  port: 12011
management:
  endpoint:
    health:
      group:
        details:
          show-components: ALWAYS
          show-details: ALWAYS
          include:
            - ping
            - db
            - redis
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - '*'
springdoc:
  # description
  version: @project.version@
  title: @project.name@
  description: @project.description@
  license-name: 'MIT'
  license-url: 'https://github.com/marcoshssilva/MHPasswordManager/blob/main/LICENSE'
  # enable actuator to Swagger
  show-actuator: true
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db_passwords;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  session:
    store-type: none
---
spring:
  config:
    activate:
      on-profile: redis
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    password: MARCOSHSSILVA#20230101
    port: 6379