spring:
  application:
    name: 'users'
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=db_users}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}

server:
  port: ${PORT:0}