---
- name: Testing connection
  hosts: server-3.marcoshssilva.com.br
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world