---
- name: Deploy DEV-ENVIRONMENT in server
  hosts: example.of.host
  tasks:
    - name: Ping my host
      ansible.builtin.ping:
    - name: Delete remaining file from old deploy
      ansible.builtin.file:
        path: /tmp/config-mypass-dev-cloud-dns-ph.zip
        state: absent
    - name: Downloading new deploy configs
      get_url:
        url: 'https://nexus.apps.marcoshssilva.com.br/repository/raw-data/mypass-dev-cloud-dns-ph/docker/config-mypass-dev-cloud-dns-ph.zip'
        dest: /tmp/config-mypass-dev-cloud-dns-ph.zip
        headers:
          Authorization: 'Basic {{ NEXUS3_PASSWORD }}'
    - name: Shutdown current application
      changed_when: true
      ansible.builtin.shell: |
        cd /home/ubuntu/my-pass-dev/config-mypass-dev
        sh shutdown
    - name: Move folder old data to new directory with date
      changed_when: true
      ansible.builtin.shell: mv /home/ubuntu/my-pass-dev/config-mypass-dev /home/ubuntu/my-pass-dev/config-mypass-dev-$(date +%Y%m%d-%H%M%S)
      args:
        executable: /bin/bash
    - name: Unzip downloaded files
      changed_when: true
      ansible.builtin.shell: |
        cd /tmp
        unzip -o config-mypass-dev-cloud-dns-ph.zip -d /home/ubuntu/my-pass-dev/config-mypass-dev
    - name: Starting services
      changed_when: true
      ansible.builtin.shell: |
        cd /tmp
        unzip -o config-mypass-dev-cloud-dns-ph.zip -d /home/ubuntu/my-pass-dev/config-mypass-dev
        cd /home/ubuntu/my-pass-dev/config-mypass-dev
        sh startup
      args:
        executable: /bin/bash
