---
- name: Deploy DEV-ENVIRONMENT in server
  hosts: server-3.marcoshssilva.com.br
  tasks:
    - name: Ping my host
      ansible.builtin.ping:
    - name: Install packages
      ansible.builtin.apt:
        state: present
        pkg:
          - zip
          - unzip
          - tar
    - name: Delete remaining file from old deploy
      ansible.builtin.file:
        path: /home/ubuntu/config-mypass-dev-cloud-dns-ph.zip
        state: absent
    - name: Delete remaining directory from old deploy
      ansible.builtin.file:
        path: /home/ubuntu/config-mypass-dev
        state: absent
    - name: Downloading new deploy configs
      get_url:
        url: 'https://nexus.apps.marcoshssilva.com.br/repository/raw-data/mypass-dev-cloud-dns-ph/docker/config-mypass-dev-cloud-dns-ph.zip'
        dest: /home/ubuntu/config-mypass-dev-cloud-dns-ph.zip
        headers:
          Authorization: 'Basic {{ NEXUS3_PASSWORD }}'
    - name: Give permissions to file
      ansible.builtin.file:
        path: /home/ubuntu/config-mypass-dev-cloud-dns-ph.zip
        owner: ubuntu
        group: ubuntu
        mode: '0755'
    - name: Unzip downloaded files
      ansible.builtin.unarchive:
        src: /home/ubuntu/config-mypass-dev-cloud-dns-ph.zip
        dest: /home/ubuntu/config-mypass-dev
